trigger:
- master

variables:
  - group: vlc
  - name: BuildConfiguration
    value: Release

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  displayName: Get config
  inputs:
    filePath: 'azure-pipelines.get-config.ps1'
    failOnStderr: true

## Crawler ######################################################################
- task: DotNetCoreCLI@2
  displayName: Build crawler
  inputs:
    command: 'pack'
    projects: 'Crawler\VlcCrawler.sln'
    versioningScheme: 'off'

- task: CopyFiles@2
  displayName: Copy crawler to artifacts
  inputs:
    Contents: 'Crawler\VlcCrawler\bin\Release\**\publish\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Crawler'

- task: PublishBuildArtifacts@1
  displayName: Publish crawler artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Crawler'
    ArtifactName: 'Crawler'
    publishLocation: 'Container'


## Docker ######################################################################
- task: DownloadFile@1
  displayName: Download VLC
  inputs:
    FileUrl: 'https://download.videolan.org/pub/videolan/vlc/$(vlc.version)/win64/vlc-$(vlc.version)-win64.zip'
    DestinationFolder: '$(System.DefaultWorkingDirectory)'
    requireAuthentication: false

- task: RegexReplace@3
  displayName: Generate Dockerfile for the given version
  inputs:
    InputSearchPattern: 'Dockerfile'
    FindRegex: '\{vlc\.version\}'
    ReplaceRegex: '$(vlc.version)'
    UseUTF8: true

- task: CopyFiles@2
  displayName: Copy Dockerfile and VLC zip installer to artifacts
  inputs:
    Contents: |
      config.txt
      Dockerfile
      vlc-$(vlc.version)-win64.zip
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Docker'
    
- task: PublishBuildArtifacts@1
  displayName: Publish docker artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Docker'
    ArtifactName: 'Docker'
    publishLocation: 'Container'

# This is the last task as it's the longest, and we don't needs it output
- task: Docker@2
  displayName: Validate that the generated Dockerfile is valid
  inputs:
    repository: 'dr1rrb/vlc-win'
    command: 'build'
    tags: latest

